//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magensa.DecryptV3.Services
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericMagensaInputs", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.GenerateMacRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.GenerateMacRequestV2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.DecryptCardSwipeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.DecryptCardSwipeRequestV2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.DecryptRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.DecryptRequestV2))]
    public partial class GenericMagensaInputs : object
    {
        
        private string BillingLabelField;
        
        private string CustomerTransactionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingLabel
        {
            get
            {
                return this.BillingLabelField;
            }
            set
            {
                this.BillingLabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenerateMacRequest", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.GenerateMacRequestV2))]
    public partial class GenerateMacRequest : Magensa.DecryptV3.Services.GenericMagensaInputs
    {
        
        private Magensa.DecryptV3.Services.Authentication AuthenticationField;
        
        private string DataToMACField;
        
        private string KSNField;
        
        private Magensa.DecryptV3.Services.KeyDerivationEnum KeyDerivationTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DecryptV3.Services.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataToMAC
        {
            get
            {
                return this.DataToMACField;
            }
            set
            {
                this.DataToMACField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DecryptV3.Services.KeyDerivationEnum KeyDerivationType
        {
            get
            {
                return this.KeyDerivationTypeField;
            }
            set
            {
                this.KeyDerivationTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenerateMacRequestV2", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    public partial class GenerateMacRequestV2 : Magensa.DecryptV3.Services.GenerateMacRequest
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecryptCardSwipeRequest", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.DecryptCardSwipeRequestV2))]
    public partial class DecryptCardSwipeRequest : Magensa.DecryptV3.Services.GenericMagensaInputs
    {
        
        private Magensa.DecryptV3.Services.Authentication AuthenticationField;
        
        private Magensa.DecryptV3.Services.EncryptedCardSwipe EncryptedCardSwipeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.DecryptV3.Services.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.DecryptV3.Services.EncryptedCardSwipe EncryptedCardSwipe
        {
            get
            {
                return this.EncryptedCardSwipeField;
            }
            set
            {
                this.EncryptedCardSwipeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecryptCardSwipeRequestV2", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    public partial class DecryptCardSwipeRequestV2 : Magensa.DecryptV3.Services.DecryptCardSwipeRequest
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecryptRequest", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.DecryptRequestV2))]
    public partial class DecryptRequest : Magensa.DecryptV3.Services.GenericMagensaInputs
    {
        
        private Magensa.DecryptV3.Services.Authentication AuthenticationField;
        
        private string EncryptedDataField;
        
        private string KSNField;
        
        private Magensa.DecryptV3.Services.KeyVariantEnum KeyTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DecryptV3.Services.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EncryptedData
        {
            get
            {
                return this.EncryptedDataField;
            }
            set
            {
                this.EncryptedDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DecryptV3.Services.KeyVariantEnum KeyType
        {
            get
            {
                return this.KeyTypeField;
            }
            set
            {
                this.KeyTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecryptRequestV2", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    public partial class DecryptRequestV2 : Magensa.DecryptV3.Services.DecryptRequest
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authentication", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    public partial class Authentication : object
    {
        
        private string CustomerCodeField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyVariantEnum", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    public enum KeyVariantEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Data = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyDerivationEnum", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    public enum KeyDerivationEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fixed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DUKPT = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncryptedCardSwipe", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    public partial class EncryptedCardSwipe : object
    {
        
        private string DeviceSNField;
        
        private string KSNField;
        
        private Magensa.DecryptV3.Services.KeyVariantEnum KeyTypeField;
        
        private string MagnePrintField;
        
        private string MagnePrintStatusField;
        
        private string Track1Field;
        
        private string Track2Field;
        
        private string Track3Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceSN
        {
            get
            {
                return this.DeviceSNField;
            }
            set
            {
                this.DeviceSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DecryptV3.Services.KeyVariantEnum KeyType
        {
            get
            {
                return this.KeyTypeField;
            }
            set
            {
                this.KeyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagnePrint
        {
            get
            {
                return this.MagnePrintField;
            }
            set
            {
                this.MagnePrintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagnePrintStatus
        {
            get
            {
                return this.MagnePrintStatusField;
            }
            set
            {
                this.MagnePrintStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track1
        {
            get
            {
                return this.Track1Field;
            }
            set
            {
                this.Track1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track2
        {
            get
            {
                return this.Track2Field;
            }
            set
            {
                this.Track2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track3
        {
            get
            {
                return this.Track3Field;
            }
            set
            {
                this.Track3Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicTransactionInfo", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.GenerateMACResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.GenerateMACResponseV2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.DecryptCardSwipeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.DecryptCardSwipeResponseV2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.DecryptResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.DecryptResponseV2))]
    public partial class BasicTransactionInfo : object
    {
        
        private string CustomerTransactionIdField;
        
        private bool IsReplayField;
        
        private string MagTranIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionId
        {
            get
            {
                return this.CustomerTransactionIdField;
            }
            set
            {
                this.CustomerTransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReplay
        {
            get
            {
                return this.IsReplayField;
            }
            set
            {
                this.IsReplayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranId
        {
            get
            {
                return this.MagTranIdField;
            }
            set
            {
                this.MagTranIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenerateMACResponse", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.GenerateMACResponseV2))]
    public partial class GenerateMACResponse : Magensa.DecryptV3.Services.BasicTransactionInfo
    {
        
        private string MACedStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MACedString
        {
            get
            {
                return this.MACedStringField;
            }
            set
            {
                this.MACedStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenerateMACResponseV2", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    public partial class GenerateMACResponseV2 : Magensa.DecryptV3.Services.GenerateMACResponse
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalResponseDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalResponseData
        {
            get
            {
                return this.AdditionalResponseDataField;
            }
            set
            {
                this.AdditionalResponseDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecryptCardSwipeResponse", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.DecryptCardSwipeResponseV2))]
    public partial class DecryptCardSwipeResponse : Magensa.DecryptV3.Services.BasicTransactionInfo
    {
        
        private string CardIDField;
        
        private Magensa.DecryptV3.Services.DecryptedCardSwipe DecryptedCardSwipeField;
        
        private decimal MagnePrintScoreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardID
        {
            get
            {
                return this.CardIDField;
            }
            set
            {
                this.CardIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.DecryptV3.Services.DecryptedCardSwipe DecryptedCardSwipe
        {
            get
            {
                return this.DecryptedCardSwipeField;
            }
            set
            {
                this.DecryptedCardSwipeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MagnePrintScore
        {
            get
            {
                return this.MagnePrintScoreField;
            }
            set
            {
                this.MagnePrintScoreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecryptCardSwipeResponseV2", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    public partial class DecryptCardSwipeResponseV2 : Magensa.DecryptV3.Services.DecryptCardSwipeResponse
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalResponseDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalResponseData
        {
            get
            {
                return this.AdditionalResponseDataField;
            }
            set
            {
                this.AdditionalResponseDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecryptResponse", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.DecryptV3.Services.DecryptResponseV2))]
    public partial class DecryptResponse : Magensa.DecryptV3.Services.BasicTransactionInfo
    {
        
        private string DecryptedDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DecryptedData
        {
            get
            {
                return this.DecryptedDataField;
            }
            set
            {
                this.DecryptedDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecryptResponseV2", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    public partial class DecryptResponseV2 : Magensa.DecryptV3.Services.DecryptResponse
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalResponseDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalResponseData
        {
            get
            {
                return this.AdditionalResponseDataField;
            }
            set
            {
                this.AdditionalResponseDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecryptedCardSwipe", Namespace="http://schemas.datacontract.org/2004/07/Decrypt.Core")]
    public partial class DecryptedCardSwipe : object
    {
        
        private string MagnePrintField;
        
        private string Track1Field;
        
        private string Track2Field;
        
        private string Track3Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagnePrint
        {
            get
            {
                return this.MagnePrintField;
            }
            set
            {
                this.MagnePrintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track1
        {
            get
            {
                return this.Track1Field;
            }
            set
            {
                this.Track1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track2
        {
            get
            {
                return this.Track2Field;
            }
            set
            {
                this.Track2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track3
        {
            get
            {
                return this.Track3Field;
            }
            set
            {
                this.Track3Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Magensa.DecryptV3.Services.IDecryptV2")]
    public interface IDecryptV2
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptV2/DecryptData", ReplyAction="http://tempuri.org/IDecryptV2/DecryptDataResponse")]
        System.Threading.Tasks.Task<Magensa.DecryptV3.Services.DecryptResponseV2> DecryptDataAsync(Magensa.DecryptV3.Services.DecryptRequestV2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptV2/GenerateMac", ReplyAction="http://tempuri.org/IDecryptV2/GenerateMacResponse")]
        System.Threading.Tasks.Task<Magensa.DecryptV3.Services.GenerateMACResponseV2> GenerateMacAsync(Magensa.DecryptV3.Services.GenerateMacRequestV2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptV2/DecryptCardSwipe", ReplyAction="http://tempuri.org/IDecryptV2/DecryptCardSwipeResponse")]
        System.Threading.Tasks.Task<Magensa.DecryptV3.Services.DecryptCardSwipeResponseV2> DecryptCardSwipeAsync(Magensa.DecryptV3.Services.DecryptCardSwipeRequestV2 request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IDecryptV2Channel : Magensa.DecryptV3.Services.IDecryptV2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DecryptV2Client : System.ServiceModel.ClientBase<Magensa.DecryptV3.Services.IDecryptV2>, Magensa.DecryptV3.Services.IDecryptV2
    {
        
        public DecryptV2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Magensa.DecryptV3.Services.DecryptResponseV2> DecryptDataAsync(Magensa.DecryptV3.Services.DecryptRequestV2 request)
        {
            return base.Channel.DecryptDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.DecryptV3.Services.GenerateMACResponseV2> GenerateMacAsync(Magensa.DecryptV3.Services.GenerateMacRequestV2 request)
        {
            return base.Channel.GenerateMacAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.DecryptV3.Services.DecryptCardSwipeResponseV2> DecryptCardSwipeAsync(Magensa.DecryptV3.Services.DecryptCardSwipeRequestV2 request)
        {
            return base.Channel.DecryptCardSwipeAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
